M48
; DRILL file {KiCad 9.0.3} date 2025-10-02T16:46:49+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-02T16:46:49+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.790
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.020
%
G90
G05
T1
X65.435Y-80.2
X68.565Y-80.2
T2
X64.96Y-35.96
X64.96Y-74.44
M30
